# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Node.js Package

on:
  release:
    types: [created]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Packages
        run: npm ci

      - name: NG build
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ngx-toast
          path: dist


  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download built directory
        uses: actions/download-artifact@v3
        with:
          name: ngx-toast

      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      # - name: NPM login

      - name: Publish
        run: |
          cd ngx-toast
          npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download built directory
        uses: actions/download-artifact@v3
        with:
          name: ngx-toast

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - name: Pusblish GPR
        run: |
          cd ngx-toast
          npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
